### ISSUE TITLE
Booking Request Form

### ISSUE THREAD

**Issue by Llywelyn1282** [Llywelyn1282/the-dead-swan#1]
**User Story**

As a Customer, I want to be able to request a table for a meal, evening of drinking or to see live music.

**Acceptance Criteria**

- [ ] A simple and easy to use booking request form.
- [ ] The form includes all necessary fields to gather customer details: Name, Email, Phone Number, Party Number, Desired Arrival Time and Optional Message field.
- [ ] All fields on the form must be completed before the user can submit the form.
- [ ] When the form is completed correctly, the user is taken to a success page.

**Tasks**

- [ ] Implement a booking request form on the website.
- [ ] Implement HTML validation on the form to fit the requirements above.
- [ ] Create a success page to direct users to after submitting the form.
